---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: conn-test
  name: conn-test
spec:
  containers:
  - image: "nginx:{{ .Chart.AppVersion }}"
    name: conn-test
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
