apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: conn-test
spec:
  hosts:
  - {{ .Values.virtualservice.host.fqdn }}
  gateways:
  - conn-test-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: conn-test